name: Building documentation

on:
  push:
    branches:
      - dev
    paths:
      - doc/**
      - src/**
      - .github/workflows/build-documentation.yml
  pull_request:
    branches:
      - dev
    paths:
      - doc/**
      - .github/workflows/build-documentation.yml
  workflow_dispatch:

jobs:
  generate-docs:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Setup DocFX
        working-directory: doc
        run:  dotnet tool update -g docfx

      - name: DocFX Build
        working-directory: doc
        run: docfx .\docfx.json
        continue-on-error: false

      - name: Publish
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/live
          force_orphan: true
